# cloudflared tunnel --url http://localhost:6110    https://current-exhaust-misc-kinds.trycloudflare.com
 # cloudflared tunnel --url http://localhost:5110   https://boundary-resumes-occupational-horses.trycloudflare.com

ip: "127.0.0.1"
port: 7497
client_id: 110

logging_level: logging.INFO

ws_port: 6110

api_service:
  port: 5110
  host: 127.0.0.1

interval_seconds:
  engine_loop: .1
  open_trades_streamer: 1
  contract_strikes_streamer: 1
  contract_strikes_force_emit: 15
  quote_cache_streamer: 1
  quote_cache_force_emit: 15

dirs:
  default: "../../portfolios/{portfolio_id}/default"
  results: "../../portfolios/{portfolio_id}/results"
  heartbeat: "../../portfolios/{portfolio_id}/heartbeat"
  ib: "../../portfolios/{portfolio_id}/ib"
  reports: "../../portfolios/{portfolio_id}/reports"
  log_dir: "../../portfolios/{portfolio_id}/logs/{date}"
  intermediate: "../../portfolios/{portfolio_id}/intermediate"
  ohlc: "../../portfolios/{portfolio_id}/backtest-ohlc"
  ohlc_archive: "../../portfolios/{portfolio_id}/ohlc-archive"
  ohlc_w_indicators: "../../portfolios/{portfolio_id}/ohlc-w-indicators"
  charts: "../../portfolios/{portfolio_id}/charts/{date}"

files:
  application_state: "{intermediate}/application_state.json"
  account_info_map: "{intermediate}/account_info_map.json"

  drawing_objects_df: "{charts}/10-drawing_objects_df.csv"
  key_levels_df: "{results}/11-key_levels_df.csv"
  hover_df: "{charts}/12-hover_df.csv"
  close_levels_df": "{charts}/13-close_levels_df.csv"
  candle_info_df: "{charts}/14-candle_info_df.csv"
  screening_log_df: "{charts}/12-screening_log_df.csv"
  order_history_df: "{results}/13-order_history_df.csv"
  stop_loss_history_df: "{results}/14-stop_loss_history_df.csv"
  take_profit_history_df: "{results}/15-take_profit_history_df.csv"
  futures_order_history_df: "{results}/16-futures_order_history_df.csv"
  screening_log_for_run_df: "{results}/17-screening_log_for_run_df.csv" # TODO rename
  screening_summary_df: "{results}/18-screening_summary_df.csv" # TODO rename
  bid_ask_history_df: "{results}/19-bid_ask_history_df.csv" # TODO rename
  screening_summary_agg_df: "{results}/20-screening_summary_agg_df.csv" # TODO rename
  capital_allocation_df: "{results}/21-capital_allocation_df.csv" # TODO rename
  open_close_refs_df: "{results}/22-open_close_refs_df.csv" # TODO rename
  open_close_refs_pnl_df: "{results}/23-open_close_refs_pnl_df.csv" # TODO rename
  capital_flow_df: "{results}/24-capital_flow_df.csv" # TODO rename
  ib_pnl_df: "{ib}/91-ib_pnl_df.csv"

  screening_summary_for_all_sub_runs_agg_df: "{results}/25-screening_summary_for_all_sub_runs_agg_df.csv" # TODO rename
  test_df: "{results}/99-test_df.csv"

market:
  trading_hours: 930 <= current_hh_mm_ny < 1600

debug: True

indicators:
  calculation_interval_seconds: 0
  print_last_few_rows: False
  details:
    one:
      active: true
      calculation: |
        df['open_low_diff'] = df['open'] - df['low']
        df['open_low_diff_avg'] = df['open_low_diff'].rolling(30, min_periods=1).mean()
    two:
      active: true
      calculation: |
        df['high_open_diff'] = df['high'] - df['open']
        df['high_open_diff_avg'] = df['high_open_diff'].rolling(30, min_periods=1).mean()
        


entry_conditions:
  print_last_few_rows: False
  long:
    - df['open_low_diff'].iloc[-1] >  df['open_low_diff_avg'].iloc[-1]
  short:
    - df['high_open_diff'].iloc[-1] >  df['high_open_diff_avg'].iloc[-1]

exit_conditions:
  print_last_few_rows: False
  long:
    - str(df['date'].iloc[-1]) != open_candle_date
  short:
    - str(df['date'].iloc[-1]) != open_candle_date

historical_data:
  print_last_few_rows: False
